#!/bin/sh
set -e

export CC=gcc
export CXX=g++
export PKG_CONFIG_PATH="/home/half-arch/repos/mpv-build/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
export LD_LIBRARY_PATH="/home/half-arch/repos/mpv-build/build_libs/lib:$LD_LIBRARY_PATH"

make -C ffmpeg_build install "$@"
