#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"
export CC=gcc
export CXX=g++
if test -f "$BUILD"/mpv_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/mpv_options) "$@"
    unset -v IFS
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

echo Using mpv options: $OPTIONS "$@"

cd "$BUILD"/mpv

# add missing private dependencies from libass.pc
# this is necessary due to the hybrid static / dynamic nature of the build
# need to link against stdc++ in case libplacebo was built with glslang,
# which requires that
export LDFLAGS="$LDFLAGS $(pkg-config --libs fontconfig harfbuzz fribidi) -lstdc++"
export LDFLAGS="$LDFLAGS -L$BUILD/build_libs/lib $(pkg-config --libs fontconfig harfbuzz fribidi) -lstdc++"
meson setup build \
  -Dbuildtype=release \
  -Dlibmpv=true \
  -Dlua=enabled \
  -Djavascript=enabled \
  -Dalsa=enabled \
  -Dpipewire=enabled \
  -Dpulse=enabled \
  -Djack=enabled \
  -Dopenal=enabled \
  -Dsndio=enabled \
  -Dvulkan=enabled \
  -Dgl=enabled \
  -Dlibplacebo=enabled \
  -Dcaca=enabled \
  -Dkitty=enabled \
  -Dsixel=enabled \
  -Dx11=enabled \
  -Dwayland=enabled \
  -Ddrm=enabled \
  -Dgbm=enabled \
  -Degl=enabled \
  -Ddvdread=enabled \
  -Ddvdnav=enabled \
  -Dbluray=enabled \
  -Duchardet=enabled \
    $OPTIONS "$@"
